### PR TITLE
CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by Albert-Debbarma**
hello
 i have just added contribution.md file  to your repo.

### CODE REVIEW

**Comment by srkds** [comment]
Great to have your contribution to this repo 🚀

**Review by srkds — CHANGES_REQUESTED** [review]
Change filename to CONTRIBUTING.md
and change PR title to "add CONTRIBUTING.md file"

**Comment by Albert-Debbarma** [comment]
i have made the chages.

**Review by srkds — APPROVED** [review]
LGTM 👍  Thank you for your contribution 😀 🧑🏻‍💻

**Pull request merged**
